#!php
<?php

require_once("lib/shell.php");
require_once("lib/countrms/include.php");

// required for qc

require_once("qc_lib/lib/protect/sql-auth.php");
require_once("qc_lib/lib/qc-data-types/const/qcdb.php");

class My extends Shell {

    public static function help(): void {
        self::writeln("There will be no help.");
    }

    public static function main(): int {
        if (self::hasArg("count")) {
            return CountRMS::main();
        }
        if (self::hasArg("_vsi")) {
            self::writeln(implode("\n", QCDB::colDump("StkItem")));
            return 0;
        }
        if (self::hasArg("_vpp")) {
            self::writeln(implode("\n", QCDB::colDump("ProdPattern")));
        }
        self::writeln("Nothing to do.");
        self::argDump();
        return 0;
    }
}

My::main();